class_name QuestDB
## Static quest definitions: the main story of Emberfell and a side chain
## across the four village NPCs.
##
## Objective types:
##   "talk"     — talk to the NPC named in "target"
##   "kill"     — kill "target" skeletons (counted from acceptance)
##   "collect"  — hold "target" potions at once
##   "level"    — reach player level "target"
##   "reach"    — reach the [x, z, radius] in "objective_target"
##   "bosskill" — slay the boss

enum State { LOCKED, AVAILABLE, ACTIVE, COMPLETE, TURNED_IN }

const QUESTS := [
	# ---------------------------------------------------------- MAIN STORY
	{
		"id": "emberfell_arrives",
		"giver": "Old Fen",
		"title": "The Road to Emberfell",
		"main": true,
		"prereq": "",
		"objective_type": "talk",
		"objective_target": "Old Fen",
		"objective_text": "Speak with Old Fen",
		"offer": [
			"The Road to Emberfell",
			"So. The traveler from the tales stands before me at last.",
			"The dead rise in the southern wilds, and Emberfell's lamps burn low.",
			"Will you help this old keeper of stories write a better ending?",
		],
		"reminder": [
			"The wilds are waiting, traveler.",
		],
		"complete_lines": [
			"The Road to Emberfell",
			"Then it's settled. Rest up, stock your pack, and come back when you're ready.",
			"Your legend starts here — try not to die in the first chapter.",
		],
		"reward_gold": 50,
		"reward_xp": 30,
	},
	{
		"id": "what_stirs_below",
		"giver": "Old Fen",
		"title": "What Stirs Below",
		"main": true,
		"prereq": "emberfell_arrives",
		"objective_type": "kill",
		"objective_target": 8,
		"objective_text": "Defeat 8 foes",
		"offer": [
			"What Stirs Below",
			"Every skeleton you shatter is one less blade at our throats — but they're just the fingers.",
			"Something down south is making a fist. I can feel it in my bones, and my bones are never wrong.",
			"Thin the herd: 8 of them. Then we'll talk about the black water.",
		],
		"reminder": [
			"Eight skeletons, traveler. The southern wilds.",
		],
		"complete_lines": [
			"What Stirs Below",
			"Eight shattered. But you felt it too, didn't you? They weren't wandering — they were called.",
			"There's black water east of the wilds, dark as a drowned man's dream. Cross the bridge, and you'll find what's calling them.",
		],
		"reward_gold": 150,
		"reward_xp": 100,
	},
	{
		"id": "the_black_water",
		"giver": "Old Fen",
		"title": "The Black Water",
		"main": true,
		"prereq": "what_stirs_below",
		"objective_type": "reach",
		"objective_target": [37.0, 57.0, 5.0],
		"objective_text": "Cross the bridge to the island",
		"offer": [
			"The Black Water",
			"East of the wilds lies black water, and over it a bridge no living hands maintain.",
			"On the island beyond, something old wears a crown of drowned gold.",
			"Cross the bridge. See what's waiting. Then come back — if you can.",
		],
		"reminder": [
			"East, past the wilds. Cross the bridge to the island.",
		],
		"complete_lines": [
			"The Black Water",
			"You stood on the cursed isle and lived. Few can say that.",
			"Now finish it. Send Vorgath back to the dark he crawled from.",
		],
		"reward_gold": 100,
		"reward_xp": 80,
	},
	{
		"id": "the_drowned_tyrant",
		"giver": "Old Fen",
		"title": "The Drowned Tyrant",
		"main": true,
		"prereq": "the_black_water",
		"objective_type": "bosskill",
		"boss_id": "vorgath",
		"objective_target": 1,
		"objective_text": "Slay Vorgath, the Drowned King",
		"offer": [
			"The Drowned Tyrant",
			"Vorgath was a king before Emberfell had a name. The black water took him — and gave him back wrong.",
			"He calls the dead from his island throne. While he wears that crown, the wilds will never rest.",
			"End him, traveler. End this.",
		],
		"reminder": [
			"Vorgath waits on the island. Finish it.",
		],
		"complete_lines": [
			"The Drowned Tyrant",
			"The crown is silent. The wilds are quiet — for the first time in living memory.",
			"Emberfell owes you more than gold, hero. But gold is what I have.",
		],
		"reward_gold": 500,
		"reward_xp": 300,
	},
	# ---------------------------------------------------------- CHAPTER TWO
	{
		"id": "the_northern_road",
		"giver": "Old Fen",
		"title": "The Northern Road",
		"main": true,
		"prereq": "the_drowned_tyrant",
		"objective_type": "talk",
		"objective_target": "Old Fen",
		"objective_text": "Speak with Old Fen",
		"offer": [
			"The Northern Road",
			"Vorgath is gone, but the riders from Grimholt bring grim news.",
			"The northern road is overrun. The dead walk the cold wilds, bolder than ever.",
			"Grimholt needs a hero, traveler. The north gate stands open. Will you go?",
		],
		"reminder": [
			"The north gate, traveler. Grimholt is waiting.",
		],
		"complete_lines": [
			"The Northern Road",
			"Then go with my blessing. The northern wilds are cruel — dead trees, jagged rocks, and worse.",
			"Find Elder Sella in Grimholt. Tell her Emberfell remembers its friends.",
		],
		"reward_gold": 100,
		"reward_xp": 80,
	},
	{
		"id": "grimholt_bound",
		"giver": "Old Fen",
		"title": "Grimholt Bound",
		"main": true,
		"prereq": "the_northern_road",
		"objective_type": "reach",
		"objective_target": [0.0, -250.0, 10.0],
		"objective_text": "Reach Grimholt in the far north",
		"offer": [
			"Grimholt Bound",
			"North through the gate, then follow the road. It's a long walk — the wilds are bigger than ours.",
			"Stay on the road if you can. The treeline hides teeth.",
			"Grimholt's lamps burn at the far end. Don't let them go out.",
		],
		"reminder": [
			"North, traveler. Follow the road to Grimholt.",
		],
		"complete_lines": [
			"Grimholt Bound",
			"You made it. The town still stands — barely.",
			"Find Elder Sella. She'll know what needs doing.",
		],
		"reward_gold": 150,
		"reward_xp": 120,
	},
	{
		"id": "the_cold_dark",
		"giver": "Elder Sella",
		"title": "The Cold Dark",
		"main": true,
		"prereq": "grimholt_bound",
		"objective_type": "kill",
		"objective_target": 12,
		"objective_text": "Defeat 12 northern foes",
		"offer": [
			"The Cold Dark",
			"Emberfell sends us a hero. Good — we need one.",
			"The northern wilds crawl with the dead. Stronger than the southern rabble, too — the cold preserves them.",
			"Thin them: 12. Then we'll talk about what's really stirring out there.",
		],
		"reminder": [
			"Twelve of them, hero. The northern wilds.",
		],
		"complete_lines": [
			"The Cold Dark",
			"Twelve. The road breathes easier already.",
			"But this is just the beginning. Something ancient sleeps beneath the northern ice — and it's waking.",
		],
		"reward_gold": 300,
		"reward_xp": 250,
	},
	{
		"id": "the_frozen_arena",
		"giver": "Elder Sella",
		"title": "The Frozen Arena",
		"main": true,
		"prereq": "the_cold_dark",
		"objective_type": "reach",
		"objective_target": [0.0, -288.0, 9.0],
		"objective_text": "Find the frozen arena beyond the north wall",
		"offer": [
			"The Frozen Arena",
			"Beyond our north wall, where the road ends, the ice never melts — even in high summer.",
			"Our scouts speak of a circle of black ice ringed with crystals, and something moving at its heart.",
			"Morvain, the old songs call it. A golem of living ice, older than Grimholt itself.",
			"Go. Look. Then come back and tell me what you saw.",
		],
		"reminder": [
			"North of the north wall, hero. Follow the road past Grimholt.",
		],
		"complete_lines": [
			"The Frozen Arena",
			"You've seen it. Then the songs are true — Morvain wakes.",
			"If that thing walks south, Grimholt is finished. It has to end on that ice.",
		],
		"reward_gold": 200,
		"reward_xp": 180,
	},
	{
		"id": "the_frozen_heart",
		"giver": "Elder Sella",
		"title": "The Frozen Heart",
		"main": true,
		"prereq": "the_frozen_arena",
		"objective_type": "bosskill",
		"boss_id": "morvain",
		"objective_target": 1,
		"objective_text": "Shatter Morvain, the Frozen Heart",
		"offer": [
			"The Frozen Heart",
			"Morvain's heart is a shard of the first winter — crack it, and the golem falls.",
			"Bring me that shard and I'll teach you what the old mages knew: Glacial Spike.",
			"The cold answers the cold, hero. Make it answer to you.",
		],
		"reminder": [
			"Morvain waits on the black ice. Shatter it.",
		],
		"complete_lines": [
			"The Frozen Heart",
			"The shard... it's still cold. Colder than any winter I've known.",
			"A promise is a promise. Hold out your hand — and learn Glacial Spike.",
		],
		"reward_gold": 800,
		"reward_xp": 600,
		"reward_spell": "glacial_spike",
	},
	# ---------------------------------------------------------- CHAPTER THREE
	{
		"id": "the_western_road",
		"giver": "Old Fen",
		"title": "The Western Road",
		"main": true,
		"prereq": "the_frozen_heart",
		"objective_type": "talk",
		"objective_target": "Old Fen",
		"objective_text": "Speak with Old Fen",
		"offer": [
			"The Western Road",
			"Morvain's heart cracked, and something west of here felt it break.",
			"Four years ago the highlands burned. We told ourselves nobody was left up there.",
			"Last night a rider came down the west road. Half dead, and carrying a message.",
		],
		"reminder": [
			"The west gate, traveler. It has been shut a long time.",
		],
		"complete_lines": [
			"The Western Road",
			"The message was three words: Ashfall still holds.",
			"There is a garrison up there, and they have been alone since the fires. Go west.",
		],
		"reward_gold": 200,
		"reward_xp": 150,
	},
	{
		"id": "ashfall_watch",
		"giver": "Old Fen",
		"title": "Ashfall Watch",
		"main": true,
		"prereq": "the_western_road",
		"objective_type": "reach",
		"objective_target": [-210.0, 0.0, 13.0],
		"objective_text": "Reach Ashfall Watch on the west road",
		"offer": [
			"Ashfall Watch",
			"Follow the west road until the grass gives out. Then keep going.",
			"The watchtower stands where the road bends. You will see their fire before you see the tower.",
			"Whatever the reavers are, they are not the dead. These ones bleed.",
		],
		"reminder": [
			"West along the road, traveler. Look for the fire.",
		],
		"complete_lines": [
			"Ashfall Watch",
			"You found them. Four years holding a broken tower on a burnt hill.",
			"Whatever the Warden asks of you, she has earned the asking.",
		],
		"reward_gold": 250,
		"reward_xp": 200,
	},
	{
		"id": "the_reavers_toll",
		"giver": "Ilsa",
		"title": "The Reaver's Toll",
		"main": true,
		"prereq": "ashfall_watch",
		"objective_type": "kill",
		"objective_target": 14,
		"objective_text": "Defeat 14 foes in the highlands",
		"offer": [
			"The Reaver's Toll",
			"Kael takes a toll on the road. Not gold. He counts it in people.",
			"His band works in threes and fours. Kill one and the rest come running — remember that.",
			"Thin them. Fourteen. Then we can talk about the man himself.",
		],
		"reminder": [
			"Fourteen reavers, hero. They are out there on the ash.",
		],
		"complete_lines": [
			"The Reaver's Toll",
			"Fourteen. My riders have not managed fourteen in two years.",
			"Kael will have noticed. Good — I want him looking this way.",
		],
		"reward_gold": 450,
		"reward_xp": 400,
	},
	{
		"id": "the_ash_reaver",
		"giver": "Ilsa",
		"title": "The Ash Reaver",
		"main": true,
		"prereq": "the_reavers_toll",
		"objective_type": "bosskill",
		"boss_id": "kael",
		"objective_target": 1,
		"objective_text": "Bring down Kael, the Ash Reaver",
		"offer": [
			"The Ash Reaver",
			"Kael holds the end of the road, where the fire burned hottest and left glass.",
			"He fights like a raid: one rush to close, then he does not stop swinging.",
			"Hurt him badly enough and he will call the two who guard his fire. Be ready for all three.",
		],
		"reminder": [
			"West to the black glass, hero. Kael is waiting on it.",
		],
		"complete_lines": [
			"The Ash Reaver",
			"It is done. The road is open for the first time since the hills burned.",
			"My company is dead and my tower is broken, so I have nothing to give you but myself.",
			"Take me with you. I have been holding one hill for four years — I would like to see the rest.",
		],
		"reward_gold": 900,
		"reward_xp": 800,
		"reward_companion": "ilsa",
	},
	# ---------------------------------------------------------- CHAPTER FOUR
	{
		"id": "the_drowned_road",
		"giver": "Old Fen",
		"title": "The Drowned Road",
		"main": true,
		"prereq": "the_ash_reaver",
		"objective_type": "talk",
		"objective_target": "Old Fen",
		"objective_text": "Speak with Old Fen",
		"offer": [
			"The Drowned Road",
			"West is open, north is quiet, south is ours again. That leaves east.",
			"There was a road east once, and a chapel at the end of it, and a town past that.",
			"Then the water came up and stayed up. Nobody has been past the lich-gate in a lifetime.",
		],
		"reminder": [
			"The east gate, traveler. Mind your footing out there.",
		],
		"complete_lines": [
			"The Drowned Road",
			"The chapel still rings its bell. We hear it here, on a still night, and we never say so out loud.",
			"Go and find out who is ringing it.",
		],
		"reward_gold": 300,
		"reward_xp": 250,
	},
	{
		"id": "into_the_mirefen",
		"giver": "Old Fen",
		"title": "Into the Mirefen",
		"main": true,
		"prereq": "the_drowned_road",
		"objective_type": "reach",
		"objective_target": [210.0, 0.0, 13.0],
		"objective_text": "Reach the Drowned Chapel on the causeway",
		"offer": [
			"Into the Mirefen",
			"Stay on the causeway. I will say that again because people do not listen: stay on the causeway.",
			"The fen is knee-deep for a mile and then it is not, and you will not see where that changes.",
			"Follow the stones to the chapel. Whatever is ringing that bell is at the end of them.",
		],
		"reminder": [
			"East along the causeway, traveler. Follow the stones.",
		],
		"complete_lines": [
			"Into the Mirefen",
			"An order of three, keeping lamps lit for people who stopped coming a hundred years ago.",
			"Help them. Emberfell has been the last lamp on a road before.",
		],
		"reward_gold": 350,
		"reward_xp": 300,
	},
	{
		"id": "the_rotting_tide",
		"giver": "Odren",
		"title": "The Rotting Tide",
		"main": true,
		"prereq": "into_the_mirefen",
		"objective_type": "kill",
		"objective_target": 16,
		"objective_text": "Defeat 16 foes in the fen",
		"offer": [
			"The Rotting Tide",
			"Every year the water rises a hand's width, and every year more of them walk out of it.",
			"The wights were an order like ours once. They still hold their posts. That is the horror of it.",
			"Sixteen, and the causeway is walkable again. Do not let them get hold of you.",
		],
		"reminder": [
			"Sixteen, traveler. They are thickest off the stones.",
		],
		"complete_lines": [
			"The Rotting Tide",
			"Sixteen laid down. Some of them I knew the names of.",
			"There is one more thing out here, and it is the reason for all the rest.",
		],
		"reward_gold": 600,
		"reward_xp": 550,
	},
	{
		"id": "the_mire_horror",
		"giver": "Odren",
		"title": "The Mire Horror",
		"main": true,
		"prereq": "the_rotting_tide",
		"objective_type": "bosskill",
		"boss_id": "gholl",
		"objective_target": 1,
		"objective_text": "Put Gholl back under the water for good",
		"offer": [
			"The Mire Horror",
			"Past the lich-gate the causeway ends at a pool. The water there is black and it does not move.",
			"Gholl is what the fen made out of everyone it took. It goes under when it is hurt, and it comes back up behind you.",
			"It cannot be touched while it is down there. Do not waste yourself swinging at water.",
		],
		"reminder": [
			"The pool past the lich-gate, traveler. Gholl is in it.",
		],
		"complete_lines": [
			"The Mire Horror",
			"The water moved. For the first time in my life, the water moved.",
			"And something opened, back where you came from. Ask your Old Fen about the well.",
		],
		"reward_gold": 1200,
		"reward_xp": 1000,
	},
	# ---------------------------------------------------------- CHAPTER FIVE
	{
		"id": "the_well_opens",
		"giver": "Old Fen",
		"title": "What the Well Was For",
		"main": true,
		"prereq": "the_mire_horror",
		"objective_type": "talk",
		"objective_target": "Old Fen",
		"objective_text": "Speak with Old Fen",
		"offer": [
			"What the Well Was For",
			"The stone came off the well the night you killed that thing in the fen. Came off by itself.",
			"We have drawn water out of that well for eleven generations, hero. Eleven.",
			"And there are steps down it. Cut steps, going down, and nobody alive knew they were there.",
		],
		"reminder": [
			"The well, traveler. In the square. It is open.",
		],
		"complete_lines": [
			"What the Well Was For",
			"Vorgath wore a crown he took off something. The songs never say what.",
			"Morvain was old. Kael was cruel. Gholl was hungry. None of them were first.",
			"Whatever is at the bottom of my village's well was here before the village was.",
		],
		"reward_gold": 500,
		"reward_xp": 400,
	},
	{
		"id": "the_descent",
		"giver": "Old Fen",
		"title": "The Descent",
		"main": true,
		"prereq": "the_well_opens",
		"objective_type": "reach",
		"objective_target": [0.0, 190.0, 14.0],
		"objective_text": "Climb down the well into the vault",
		"offer": [
			"The Descent",
			"Go down. That is the whole of it. I have no wisdom for this one.",
			"Take the stairs slowly and keep your back to the light as long as you can.",
			"And hero — whatever talks to you down there, it is not lying to you. It just does not know.",
		],
		"reminder": [
			"Down the well, traveler. The steps are cut into the shaft.",
		],
		"complete_lines": [
			"The Descent",
			"A hall under my village. Braziers still lit. Lit, hero.",
			"Somebody has been keeping them lit.",
		],
		"reward_gold": 400,
		"reward_xp": 400,
	},
	{
		"id": "bones_of_the_vault",
		"giver": "Keeper Alwin",
		"title": "Bones of the Vault",
		"main": true,
		"prereq": "the_descent",
		"objective_type": "kill",
		"objective_target": 18,
		"objective_text": "Defeat 18 of the vault's dead",
		"offer": [
			"Bones of the Vault",
			"You'll want to mind the gallery. The lads down there get restless when the lamps gutter.",
			"Between you and me they've been restless a good while now. Since the winch went, I'd say.",
			"Eighteen of them ought to settle it. Then come back and I'll put the kettle on.",
		],
		"reminder": [
			"Eighteen, friend. Down the gallery and in the chambers.",
		],
		"complete_lines": [
			"Bones of the Vault",
			"Quieter. That's the quietest it's been since... since.",
			"You know, I can't rightly remember what year it is. Isn't that a thing to say.",
		],
		"reward_gold": 800,
		"reward_xp": 800,
	},
	{
		"id": "the_hollow_crown",
		"giver": "Keeper Alwin",
		"title": "The Hollow Crown",
		"main": true,
		"prereq": "bones_of_the_vault",
		"objective_type": "bosskill",
		"boss_id": "hollow",
		"objective_target": 1,
		"objective_text": "End the Hollow Crown on its throne",
		"offer": [
			"The Hollow Crown",
			"Don't go past the last chamber. That's where it sits. That's where it always sits.",
			"It reaches up through the floor, so don't stand still, and it steps out of the dark behind you, so don't feel safe.",
			"And it takes back what you take off it. You'll have to hit it harder than it can drink.",
			"You're going anyway, aren't you. They always go.",
		],
		"reminder": [
			"The throne at the end of the gallery, friend. It is waiting on its chair.",
		],
		"complete_lines": [
			"The Hollow Crown",
			"The crown's on the floor. Nothing's wearing it.",
			"Oh. Oh, I see. The winch never did get fixed, did it. And Maren isn't waiting on me.",
			"Go on up, hero. The light's still on up there, and it's yours. I'll put these lamps out on my way.",
		],
		"reward_gold": 2500,
		"reward_xp": 2000,
	},
	# ---------------------------------------------------------- SIDE QUESTS
	{
		"id": "hobs_watch",
		"main": false,
		"giver": "Hob",
		"title": "Hob's Watch",
		"prereq": "grimholt_bound",
		"objective_type": "kill",
		"objective_target": 6,
		"objective_text": "Defeat 6 foes",
		"offer": [
			"Hob's Watch",
			"You're the Emberfell hero? Good. I could use a hand on my rounds.",
			"The treeline near the road — that's where they gather. Six of 'em, at least.",
			"Watch yourself. They're tougher up here.",
		],
		"reminder": [
			"Six foes near the northern road, hero.",
		],
		"complete_lines": [
			"Hob's Watch",
			"Six down. The road's safer for it.",
			"You're alright, Emberfell. Here's your pay.",
		],
		"reward_gold": 180,
		"reward_xp": 140,
	},
	{
		"id": "pips_dream",
		"giver": "Pip",
		"title": "Pip's Dream",
		"main": false,
		"prereq": "",
		"objective_type": "talk",
		"objective_target": "Old Fen",
		"objective_text": "Talk to Old Fen",
		"offer": [
			"Pip's Dream",
			"I wanna be an adventurer, just like you! But Old Fen says I'm too young.",
			"Could you go talk to Old Fen for me? Maybe he'll tell you a real hero story!",
		],
		"reminder": [
			"Did you talk to Old Fen yet? He hangs around the square, telling stories.",
		],
		"complete_lines": [
			"Pip's Dream",
			"Old Fen told you about the Battle of the Ashen Field?! Wow...",
			"One day I'll be a hero too. Thanks, traveler! Take this for your trouble.",
		],
		"reward_gold": 30,
		"reward_xp": 20,
	},
	{
		"id": "bones_in_the_wild",
		"main": false,
		"giver": "Old Fen",
		"title": "Bones in the Wild",
		"prereq": "pips_dream",
		"objective_type": "kill",
		"objective_target": 5,
		"objective_text": "Defeat 5 foes",
		"offer": [
			"Bones in the Wild",
			"Pip speaks highly of you. Good — we'll need heroes before long.",
			"The skeletons in the southern wilds grow bolder every night.",
			"Drive back 5 of them. Show this village what you're made of.",
		],
		"reminder": [
			"The skeletons still trouble the southern wilds.",
		],
		"complete_lines": [
			"Bones in the Wild",
			"Five skeletons shattered. The wilds breathe a little easier tonight.",
			"You've earned this, hero. The village thanks you.",
		],
		"reward_gold": 100,
		"reward_xp": 60,
	},
	{
		"id": "stock_up",
		"main": false,
		"giver": "Bram",
		"title": "Stock Up",
		"prereq": "bones_in_the_wild",
		"objective_type": "collect",
		"objective_target": 3,
		"objective_text": "Hold 3 potions at once",
		"offer": [
			"Stock Up",
			"Heard you thinned the skeleton herd. Fine work!",
			"But listen — a hero who marches out unprepared is just a corpse with confidence.",
			"Carry 3 potions at once. Buy them at the market or pry them from skeleton hands.",
		],
		"reminder": [
			"Potions, traveler. Three of them, in your pack at the same time.",
		],
		"complete_lines": [
			"Stock Up",
			"Now that's a prepared adventurer. Skeletons drop potions too, remember.",
			"Take this gold — spend it on something sharp.",
		],
		"reward_gold": 120,
		"reward_xp": 80,
	},
	{
		"id": "proving_ground",
		"main": false,
		"giver": "Mira",
		"title": "Proving Ground",
		"prereq": "stock_up",
		"objective_type": "level",
		"objective_target": 6,
		"objective_text": "Reach level 6",
		"offer": [
			"Proving Ground",
			"So you're the one everyone's talking about. Bram says you're prepared; Fen says you're brave.",
			"But are you strong? The wilds only respect strength.",
			"Reach level 6 and come back. Then I'll believe the stories.",
		],
		"reminder": [
			"Level 6, traveler. The skeletons are waiting.",
		],
		"complete_lines": [
			"Proving Ground",
			"Level 6. I can see it in the way you carry that blade now.",
			"The village is lucky to have you. This is yours — you've earned it.",
		],
		"reward_gold": 200,
		"reward_xp": 150,
	},
	{
		"id": "miras_courage",
		"main": false,
		"giver": "Mira",
		"title": "A Mage's Courage",
		"prereq": "proving_ground",
		"objective_type": "talk",
		"objective_target": "Mira",
		"objective_text": "Speak with Mira",
		"offer": [
			"A Mage's Courage",
			"You've proven yourself in the wilds, and I've been... practicing. My frost bolts finally fly straight!",
			"Take me with you. I can fight beside you — and patch you up when the skeletons bite back.",
		],
		"reminder": [
			"Ready when you are. Just say the word and I'll pack my staff.",
		],
		"complete_lines": [
			"A Mage's Courage",
			"You won't regret this! I'll cover you from range — and keep you standing.",
			"Mira has joined your party! Check the PARTY tab.",
		],
		"reward_gold": 0,
		"reward_xp": 100,
		"reward_companion": "mira",
	},
	{
		"id": "brams_oath",
		"main": false,
		"giver": "Bram",
		"title": "A Barbarian's Oath",
		"prereq": "the_drowned_tyrant",
		"objective_type": "talk",
		"objective_target": "Bram",
		"objective_text": "Speak with Bram",
		"offer": [
			"A Barbarian's Oath",
			"You slew the Drowned King. I saw the whole thing from the shore, and my axe arm has itched ever since.",
			"A warrior like you shouldn't walk alone. Let me stand at your side — I'll break whatever stands in our way.",
		],
		"reminder": [
			"My axe is sharp and my oath is ready. Say the word.",
		],
		"complete_lines": [
			"A Barbarian's Oath",
			"HA! The wilds won't know what hit them. I fight in front — you watch my back.",
			"Bram has joined your party! Check the PARTY tab.",
		],
		"reward_gold": 0,
		"reward_xp": 150,
		"reward_companion": "bram",
	},
]

static func get_quest(quest_id: String) -> Dictionary:
	for q in QUESTS:
		if q["id"] == quest_id:
			return q
	return {}

static func quest_ids() -> Array:
	var ids := []
	for q in QUESTS:
		ids.append(q["id"])
	return ids
